name: run_unit_tests

on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - '.github/**'
      - 'llmops/**'
      - 'tests/**'


jobs:
  validate-code:
    name: job for validating code and structure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.9"
      - name: Load all build validation related dependencies
        shell: bash
        run: |
          set -e # fail on error
          python -m pip install --upgrade pip
          python -m pip install -r .github/requirements/build_validation_requirements.txt
          az version

      - name: Execute Common Unit Tests
        shell: bash
        run: |
          PYTHONPATH=. pytest tests --junitxml=junit/test-results.xml --cov=. --cov-report=xml

      - name: Publish Unit Test Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: unit-test-results
          path: "**/test-*.xml"