
llmops_config:
  pr:
    ENV_NAME: pr
    RUNTIME_NAME: 
    KEYVAULT_NAME:
    SUBSCRIPTION_ID: ${SUBSCRIPTION_ID}
    RESOURCE_GROUP_NAME: ${RESOURCE_GROUP_NAME}
    WORKSPACE_NAME: ${WORKSPACE_NAME}
    STANDARD_FLOW_PATH: flows/math_standard_flow
    EVALUATION_FLOW_PATH: flows/math_evaluation_flow

    datasets_config:
      - dataset : math_coding_pr
        PROMPT_FLOW_CONFIG_NAME: math_coding
        ENV_NAME: pr
        DATA_PURPOSE: pr_data
        DATA_PATH: data/math_data.jsonl
        DATASET_NAME: math_coding_pr
        DATASET_DESC: this dataset is for pr validation only
        
  dev:
    ENV_NAME: dev
    RUNTIME_NAME: 
    KEYVAULT_NAME: 
    SUBSCRIPTION_ID: ${SUBSCRIPTION_ID}
    RESOURCE_GROUP_NAME: ${RESOURCE_GROUP_NAME}
    WORKSPACE_NAME: ${WORKSPACE_NAME}
    STANDARD_FLOW_PATH: flows/math_standard_flow
    EVALUATION_FLOW_PATH: flows/math_evaluation_flow
    
    datasets_config:
      - dataset: math_coding_test
        PROMPT_FLOW_CONFIG_NAME: math_coding
        ENV_NAME: dev
        DATA_PURPOSE: test_data
        DATA_PATH: data/test_data.jsonl
        DATASET_NAME: math_coding_test
        RELATED_EXP_DATASET: math_coding_training
        DATASET_DESC: this dataset is for evaluating flows

      - dataset: math_coding_test
        PROMPT_FLOW_CONFIG_NAME: math_coding
        ENV_NAME: dev
        DATA_PURPOSE: test_data
        DATA_PATH: data/test_data.jsonl
        DATASET_NAME: math_coding_test
        RELATED_EXP_DATASET: math_coding_training
        DATASET_DESC: this dataset is for evaluating flows

      - dataset: math_coding_training
        PROMPT_FLOW_CONFIG_NAME: math_coding
        ENV_NAME: dev
        DATA_PURPOSE: training_data
        DATA_PATH: data/math_data.jsonl
        DATASET_NAME: math_coding_training
        DATASET_DESC: this dataset is for prompt experiments
    
    deployment_configs:
      azure_managed_endpoint:
        ENV_NAME: dev
        TEST_FILE_PATH: sample-request.json
        ENDPOINT_NAME: 
        ENDPOINT_DESC: An online endpoint serving a flow for math coding flow
        DEPLOYMENT_DESC: prompt flow deployment
        PRIOR_DEPLOYMENT_NAME: 
        PRIOR_DEPLOYMENT_TRAFFIC_ALLOCATION: 
        CURRENT_DEPLOYMENT_NAME: 
        CURRENT_DEPLOYMENT_TRAFFIC_ALLOCATION: "100"
        DEPLOYMENT_VM_SIZE: Standard_F4s_v2
        DEPLOYMENT_INSTANCE_COUNT: 1
        ENVIRONMENT_VARIABLES: 
          example-name: example-value

      kubernetes_endpoint:
        ENV_NAME: dev
        TEST_FILE_PATH: sample-request.json
        ENDPOINT_NAME: 
        ENDPOINT_DESC: An kubernetes endpoint serving a flow for math coding
        DEPLOYMENT_DESC: prompt flow deployment
        PRIOR_DEPLOYMENT_NAME: 
        PRIOR_DEPLOYMENT_TRAFFIC_ALLOCATION: 
        CURRENT_DEPLOYMENT_NAME: 
        CURRENT_DEPLOYMENT_TRAFFIC_ALLOCATION: 100
        COMPUTE_NAME: 
        DEPLOYMENT_VM_SIZE: promptinstancetype
        DEPLOYMENT_INSTANCE_COUNT: 1
        CPU_ALLOCATION: 
        MEMORY_ALLOCATION: 
        ENVIRONMENT_VARIABLES: 
        example-name: example-value

      webapp_endpoint:
        ENV_NAME: dev
        TEST_FILE_PATH: sample-request.json
        CONNECTION_NAMES:
          - aoai
        REGISTRY_NAME: 
        REGISTRY_RG_NAME: 
        APP_PLAN_NAME:
        WEB_APP_NAME: 
        WEB_APP_RG_NAME:
        WEB_APP_SKU: "B3"
        USER_MANAGED_ID: 


  mapping_config:
    experiment:
      math_question: ${data.question}
    evaluation:
      math_evaluation_flow:
        groundtruth: ${data.groundtruth}
        prediction: ${run.outputs.answer}




